---
Name: signify-te-reo-tooltips
---

SilverStripe\CMS\Controllers\ContentController:
      extensions:
        - Signify\TeReoTooltips\ThemeSetterExtension

SilverStripe\SiteConfig\SiteConfig:
      extensions:
        - Signify\TeReoTooltips\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
      extensions:
        - Signify\TeReoTooltips\SiteTreeExtension

#This can be altered to insert a custom colour, will not validate input value. e.g. '#D34324'
Signify\TeReoTooltips\SiteTreeExtension:
      custom_hexcode:
        0